general_configuration:
  image_size: [256, 256]
  crop_size: [224, 224] # If the backbone is "efficientnet" the crop_size is setted as the size of the model's input
  valid_extensions: [".bmp", ".BMP", ".png", ".PNG"]
  flag_threshold: False # If this flag is True the manual threshold is selected, otherwise automatic threshold 
  manual_threshold: 0.5
  precision: 32-true

dataset_pipeline:
  # ---------------------------------------------------------
  # Dataset Versioning
  # ALWAYS update this version whenever you recreate the dataset
  # ---------------------------------------------------------
  dataset_version: 3.0.0
  split_source: True ## Set to False if you have already splited the dataset source into training and validation
  seed: 42
  paths:
    source_unsplitted_dataset: "D:/emanuele/Code/dataset/src_dataset"
    source_training: "D:/emanuele/Code/dataset/dataset_splitted/training"
    source_validation: "D:/emanuele/Code/dataset/dataset_splitted/validation"
    dest_transfer_learning: "./data/dataset_tl"
    dest_patchcore: "./data/reda"

  classes:
    good_categories: ["good","dust"]
    test_only_good_categories: []
    defect_categories: ["nodi", "paglie"]

  ratios:
    training_ratio: 0.6
    tl_allocation_ratio: 0.4
    good_stress_multiplier: 2
    cimossa_undersampling_ratio: 0.40
    good_limit_patchcore: 300

  augmentation_params:
    prob_h_flip: 0.5
    prob_v_flip: 0.5
    prob_rot_180: 0.5
    color_jitter_prob: 0.3
    gaussian_noise_prob: 0.2
    gaussian_blur_prob: 0.2
    prob_stress: 0.5
    textile_intensity_range: [0.05, 0.15]
    textile_waves_range: [2.0, 5.0]
    textile_force_range: [2.0, 8.0]
    image_height: 512
    image_width: 512

model_architecture:
  # Attention: RD4AD requires ResNet-based architectures (e.g., resnet18, resnet50, wide_resnet50_2) to properly extract hierarchical feature maps.
  backbone: "wide_resnet50_2" 
  
  # Attention: RD4AD strictly requires exactly 3 consecutive layers (layer1, layer2, layer3). 
  # This is a hard structural constraint imposed by the multi-scale One-Class Bottleneck Embedding (OCBE) block.
  layers: ["layer2", "layer3"]
  weights: "DEFAULT"

transfer_learning:
  data_dir: "./data/dataset_supcon"
  num_epochs: 10
  batch_size: 32
  learning_rate: 0.0001
  temperature: 0.07
  out_dim: 128
  save_dir: "custom_weights"
  balancing_dataset: False

datamodule_configuration:
  root: "/Users/boqian/Downloads/anamoly detetion challanges/datasets"
  category: "RAW_FABRID_small"
  batch_size: 8
  num_workers: 4

# ---------------------------------------------------------
# Model-Specific Configurations
# ONLY check and modify the section of your target model
# --------------------------------------------------------- 
patchcore_configuration:
  num_epochs: 1
  train_batch_size: 32
  eval_batch_size: 32
  coreset_sampling_ratio: 0.1
  num_nearest_neighbors: 7

efficientad_configuration:
  imagenette_dir: "./data/imagenette_for_efficientad"
  num_epochs: 2
  train_batch_size: 1 # Efficient AD require a fixed batch size equal to 1 to correctly handling the knowledge distillation
  eval_batch_size: 32
  model_size: "m"
  learning_rate: 0.00013
  weight_decay: 6.7e-05

reversedistillation_configuration:
  num_epochs: 2
  train_batch_size: 64
  eval_batch_size: 64
  learning_rate: 0.005
  weight_decay: 0.0001
  optimizer: "adamw"  # Options: "adamw", "sgd", "adam"

supersimplenet_configuration:
  num_epochs: 10      
  train_batch_size: 4
  eval_batch_size: 8
  learning_rate: 0.0001      
  weight_decay: 0.00001
  supervised: False
  perlin_threshold: 0.2


# ---------------------------------------------------------
# Output Paths
# ALWAYS check and update these paths when switching models
# (e.g., change "Patchcore" to "EfficientAD" or "RD4AD")
# ---------------------------------------------------------
paths:
  # The symbolic link (symlink) path for the latest run results.
  # Choose the path corresponding to the active model architecture:
  # - For RD4AD: results/RverseDistillation/textiles_dataset/latest
  # - For Patchcore: results/Patchcore/textiles_dataset/latest
  # - For EfficientAD: results/EfficientAD/textiles_dataset/latest
  # - For SuperSimpleNet: results/SuperSimpleNet/textiles_dataset/latest
  symlink_path: "results/EfficientAd/textiles_dataset/latest"
  anomaly_images: "results/EfficientAd/anomaly_images"
  report_path: "results/EfficientAd/report"
  auroc_path: "results/EfficientAd/AUROC"
  eda_path: "results/EDA"
  benchmark_pareto_front_patchcore: "results/benchmark/benchmark_pareto_front_patchcore.csv"
  benchmark_pareto_front_efficientad: "results/benchmark/benchmark_pareto_front_efficientad.csv"
  checkpoint_destination: "checkpoints/EfficientAd-tested.ckpt"
  exports_onnx_path: "exports/efficientad_onnx"
  exports_pt_path: "exports/efficientad_pt"
  config_src_path: "config.yaml"
  config_dst_path: "results/EfficientAd/config"
